# Generated by Django 4.2.1 on 2023-05-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('cover_photo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('book_file', models.FileField(default='', upload_to='files/')),
            ],
            options={
                'ordering': ['issue_date'],
            },
        ),
    ]
