# Generated by Django 4.2.1 on 2023-07-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='categories',
            new_name='category',
        ),
    ]
