# Generated by Django 4.2.1 on 2023-07-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_categories_books_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='description',
        ),
    ]
