# Generated by Django 4.2.1 on 2023-05-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_studentbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
