# Generated by Django 4.2.1 on 2023-07-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customuser_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='group',
            new_name='group_id',
        ),
    ]
