# Generated by Django 4.2.1 on 2023-05-13 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_books_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='likes',
        ),
    ]
