# Generated by Django 4.2.1 on 2023-07-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_group_id_customuser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
