# Generated by Django 4.2.1 on 2023-07-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customuser_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='isbn_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
