# Generated by Django 4.2.1 on 2023-07-12 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customuser_gender_alter_customuser_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Group',
        ),
    ]
