# Generated by Django 4.2.1 on 2023-07-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_books_isbn_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
