# Generated by Django 4.2.1 on 2023-06-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_issuebook_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
