# Generated by Django 4.2.1 on 2023-06-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_issuebook_return_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='return_date',
            new_name='expected_return_date',
        ),
    ]
