# Generated by Django 4.2.1 on 2023-08-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_books_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_discription',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(default=None, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn_number',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
    ]
