# Generated by Django 4.2.1 on 2023-06-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_return_date_issuebook_expected_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='expected_return_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
