# Generated by Django 4.2.1 on 2023-06-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_issuebook_expected_return_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuebook',
            options={'ordering': ['user_id', 'book_id', 'issue_date', 'expected_return_date']},
        ),
    ]
