# Generated by Django 4.2.1 on 2023-06-11 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_issuebook_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuebook',
            options={},
        ),
    ]
