# Generated by Django 4.2.1 on 2023-06-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_issuebook_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='returned_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
