# Generated by Django 4.2.1 on 2023-08-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_books_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(default='no file choosen', upload_to='files/'),
        ),
    ]
