# Generated by Django 4.2.1 on 2023-08-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_books_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_descriptions',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
