# Generated by Django 4.2.1 on 2023-08-03 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_books_file_books_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_descriptions',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='fill the id number!')]),
        ),
    ]
