# Generated by Django 4.2.1 on 2023-06-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_books_price_books_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='quantity_issued',
            field=models.IntegerField(default=1),
        ),
    ]
