# Generated by Django 4.2.1 on 2024-08-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_contactus_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
