# Generated by Django 4.2.1 on 2024-09-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_customuser_father_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
